[pytest]
asyncio_mode = strict

markers =
    integration: marks tests that require running WP2, WP4 services (deselect with -m "not integration")

filterwarnings =
    ignore::starlette.exceptions.StarletteDeprecationWarning
